**Nama :** Hadie Pratama Tulili

**NIM :** 2109106043

***POSTTEST 7***

### Import Libary Tensorflow

In [47]:
import tensorflow as tf

#### Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [48]:
random_tensor = tf.random.normal([5,5], seed = 1)
print("random_tensor : \n", random_tensor.numpy())

random_tensor : 
 [[-0.3744468   0.61860144 -0.6192134   0.9124507   0.6950061 ]
 [-0.17951003 -0.37561563 -0.1350087   0.6676718   0.4242158 ]
 [-0.31347093 -0.27241856  1.1854254   0.34320396  1.4505777 ]
 [-0.29796734 -1.4172324   0.6069386  -1.4060947  -0.8780423 ]
 [-0.4037651   0.37089893 -1.0725715  -0.7477049  -1.1893758 ]]


#### Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [49]:
prime_tensor = tf.constant([[2, 3, 5, 7, 11],[13, 17, 19, 23, 29],[31, 37, 41, 43, 47],[53, 59, 61, 71, 73],[79, 83, 89, 97, 101]], shape = [5,5], dtype = tf.float32)
print("prime_tensor : \n", prime_tensor.numpy())

prime_tensor : 
 [[  2.   3.   5.   7.  11.]
 [ 13.  17.  19.  23.  29.]
 [ 31.  37.  41.  43.  47.]
 [ 53.  59.  61.  71.  73.]
 [ 79.  83.  89.  97. 101.]]


### Tampilkan dimensi dari kedua variable tersebut

In [50]:
random_tensor.get_shape()

TensorShape([5, 5])

In [60]:
prime_tensor.shape

TensorShape([5, 5])

### Tampilkan hasil dari perhitungan aritmatika 2 variable tersebut (Gunakan minimal 5 operator)

In [59]:
print("1. Penjumlahan :\n", tf.add(prime_tensor,random_tensor))
print("\n2. Pengurangan :\n", tf.subtract(prime_tensor,random_tensor))
print("\n3. Perkalian   :\n", tf.multiply(prime_tensor,random_tensor))
print("\n4. Pembagian   :\n", tf.divide(prime_tensor,random_tensor))
print("\n5. Pangkat     :\n", tf.pow(prime_tensor,random_tensor))

1. Penjumlahan :
 tf.Tensor(
[[ 1.6255531  3.6186013  4.3807864  7.912451  11.695006 ]
 [12.82049   16.624384  18.864992  23.667671  29.424215 ]
 [30.68653   36.72758   42.185425  43.343204  48.450577 ]
 [52.702034  57.582767  61.606937  69.5939    72.121956 ]
 [78.59624   83.370895  87.92743   96.2523    99.81062  ]], shape=(5, 5), dtype=float32)

2. Pengurangan :
 tf.Tensor(
[[  2.3744469   2.3813987   5.6192136   6.087549   10.304994 ]
 [ 13.17951    17.375616   19.135008   22.332329   28.575785 ]
 [ 31.31347    37.27242    39.814575   42.656796   45.549423 ]
 [ 53.297966   60.417233   60.393063   72.4061     73.878044 ]
 [ 79.40376    82.629105   90.07257    97.7477    102.18938  ]], shape=(5, 5), dtype=float32)

3. Perkalian   :
 tf.Tensor(
[[  -0.7488936    1.8558043   -3.096067     6.3871546    7.6450667]
 [  -2.3336303   -6.3854656   -2.565165    15.356451    12.302258 ]
 [  -9.717599   -10.079487    48.60244     14.757771    68.177155 ]
 [ -15.79227    -83.616714    37.023254 

### Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [53]:
print ("Nilai maksimal baris dari random_tensor : ", tf.argmax(random_tensor, axis=0).numpy())
print ("Nilai maksimal kolom dari random_tensor : ", tf.argmax(random_tensor, axis=1).numpy())

Nilai maksimal baris dari random_tensor :  [1 0 2 0 2]
Nilai maksimal kolom dari random_tensor :  [3 3 4 2 1]


In [54]:
print ("Nilai minimal baris dari random_tensor : ", tf.argmin(random_tensor, axis=0).numpy())
print ("Nilai minimal kolom dari random_tensor : ", tf.argmin(random_tensor, axis=1).numpy())

Nilai minimal baris dari random_tensor :  [4 3 4 3 4]
Nilai minimal kolom dari random_tensor :  [2 1 0 1 4]


### Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [55]:
print("Penggabungan baris dari random_tensor dan prime_tensor : \n", tf.concat([random_tensor,prime_tensor], axis=0).numpy())

Penggabungan baris dari random_tensor dan prime_tensor : 
 [[ -0.3744468    0.61860144  -0.6192134    0.9124507    0.6950061 ]
 [ -0.17951003  -0.37561563  -0.1350087    0.6676718    0.4242158 ]
 [ -0.31347093  -0.27241856   1.1854254    0.34320396   1.4505777 ]
 [ -0.29796734  -1.4172324    0.6069386   -1.4060947   -0.8780423 ]
 [ -0.4037651    0.37089893  -1.0725715   -0.7477049   -1.1893758 ]
 [  2.           3.           5.           7.          11.        ]
 [ 13.          17.          19.          23.          29.        ]
 [ 31.          37.          41.          43.          47.        ]
 [ 53.          59.          61.          71.          73.        ]
 [ 79.          83.          89.          97.         101.        ]]


In [56]:
print("Penggabungan kolom dari random_tensor dan prime_tensor : \n", tf.concat([random_tensor,prime_tensor], axis=1).numpy())

Penggabungan kolom dari random_tensor dan prime_tensor : 
 [[ -0.3744468    0.61860144  -0.6192134    0.9124507    0.6950061
    2.           3.           5.           7.          11.        ]
 [ -0.17951003  -0.37561563  -0.1350087    0.6676718    0.4242158
   13.          17.          19.          23.          29.        ]
 [ -0.31347093  -0.27241856   1.1854254    0.34320396   1.4505777
   31.          37.          41.          43.          47.        ]
 [ -0.29796734  -1.4172324    0.6069386   -1.4060947   -0.8780423
   53.          59.          61.          71.          73.        ]
 [ -0.4037651    0.37089893  -1.0725715   -0.7477049   -1.1893758
   79.          83.          89.          97.         101.        ]]


### Tampilkan hasil sorting dari kedua variable di atas. (descending)

#### random_tensor

In [57]:
sort_random_tensor = tf.sort(random_tensor, direction="DESCENDING")
print("Sorting random_tensor : \n", sort_random_tensor.numpy())

Sorting random_tensor : 
 [[ 0.9124507   0.6950061   0.61860144 -0.3744468  -0.6192134 ]
 [ 0.6676718   0.4242158  -0.1350087  -0.17951003 -0.37561563]
 [ 1.4505777   1.1854254   0.34320396 -0.27241856 -0.31347093]
 [ 0.6069386  -0.29796734 -0.8780423  -1.4060947  -1.4172324 ]
 [ 0.37089893 -0.4037651  -0.7477049  -1.0725715  -1.1893758 ]]


#### prime_tensor

In [58]:
sort_prime_tensor1 = tf.argsort(prime_tensor, direction="DESCENDING")
print("Sorting prime_tensor : \n", sort_prime_tensor1.numpy())

Sorting prime_tensor : 
 [[4 3 2 1 0]
 [4 3 2 1 0]
 [4 3 2 1 0]
 [4 3 2 1 0]
 [4 3 2 1 0]]
